name: Build and Release

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: dtolnay/rust-toolchain@stable
        name: Setup Rust
      - run: cargo build --release
        name: Build
      - uses: actions/upload-artifact@v4
        name: Upload built binary
        with:
          name: miband4-gtk
          path: target/release/miband4-gtk
      - if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        name: Create release
        with:
          files: target/release/miband4-gtk