name: Build and Release

on:
  push:
    tags:
      - "v*.*"
  workflow-dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      content: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: dtolnay/rust-toolchain@stable
        name: Setup Rust
      - run: cargo build --release
        name: Build
      - uses: actions/upload-artifact@v4
        name: Upload built binary
        with:
          name: mi-band-4-gtk
          path: target/release/mi_band_gtk